Add support for announcing services
fxbox/multicast-dns pull request #11
Opened 2020-02-15 20:26 UTC by alesharik

This PR is a fork of #10 with fixed CI build, updated dependencies, warning and deprecation cleanup

2020-02-23 09:44 UTC, alesharik commented
@azasypkin any updates on merging this?

2020-02-24 20:31 UTC, azasypkin requested changes
Sorry for the delay, I just don't actively maintain/use this repo anymore. The change looks reasonable, just two tiny nits before we can merge it and publish new version.

The code base is very old and inefficient one, and obviously needs some love :slightly_smiling_face: 

Thanks for the contribution!

2020-02-24 20:31 UTC, azasypkin commented on src/adapters/avahi/adapter.rs
> +                -1,
__nit:__
```suggestion
                AvahiIfIndex::AVAHI_IF_UNSPEC,
```

2020-02-24 20:31 UTC, azasypkin commented on src/bindings/avahi/functions.rs
> +        interface: c_int,
__nit:__
```suggestion
        interface: AvahiIfIndex,
```

2020-02-25 19:23 UTC, azasypkin approved these changes
LGTM

2020-02-25 19:24 UTC, merged

2020-02-25 20:18 UTC, andir commented
Thanks!